### ISSUE TITLE
Android 10 (qp1a) 设备上闪退

### ISSUE THREAD

**Issue by entr0pia** [ekibun/QQNotifyPlus#13]
Android 10 第一个正式版, pixel 2, 该应用无法正常工作

**Comment by xa0082249956** [comment]
最新版 QQ 貌似原生支持通知分离，可以先苟着。

**Comment by entr0pia** [comment]
> 最新版 QQ 貌似原生支持通知分离，可以先苟着。------------------ 原始邮件 ------------------ 发件人: "风沐白"<notifications@github.com> 发送时间: 2019年9月4日(星期三) 下午4:37 收件人: "ekibun/QQNotifyPlus"<QQNotifyPlus@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [ekibun/QQNotifyPlus] Android 10 (qp1a) 设备上闪退 (#13) Android 10 第一个正式版, pixel 2, 该应用无法正常工作 &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

我还在坚持play版776
