### ISSUE TITLE
使用 Tim 会弹出两条通知

### ISSUE THREAD

**Issue by ShadowLyin** [ekibun/QQNotifyPlus#2]
一条原通知，一条替换后的通知，而后原通知会自行消失。
已开启无障碍、通知使用权、并授予root权限，并通过systemize转为系统应用。
tim版本：`2.3.1`
qq通知增强版本：`alpha20190310`
系统版本：`PixelExperience_enchilada-9.0-20190305-1833-OFFICIAL (oneplus 6)`
magisk版本：`v18.1`

**Comment by stiven-ding** [comment]
I don't have root access and I just set the notification by TIM "show silently" to solve this problem.

(My phone is running Android P)

**Comment by ekibun** [comment]
root有延迟，把原通知优先级调低就好

**Comment by ShadowLyin** [comment]
好的，目前这样就正常了。
