### ISSUE TITLE
通知图标问题

### ISSUE THREAD

**Issue by MisakaSakura** [ekibun/QQNotifyPlus#4]
现在的通知虽然完美接替QQ自带的，但是只能显示某个发送消息人的名字的首字母/字作为消息通知的图标，不知道可否让程序连同发送人的头像也接替下来作为弹出通知的图标？如果表述不清可以发邮件

**Comment by ekibun** [comment]
办不到，通知里面没有发送人头像的信息，所以我才很讨厌Android9的通知样式。。

**Comment by MisakaSakura** [comment]
@ekibun 意思是之前的Android版本可以做到是吧？感谢解惑

**Comment by ekibun** [comment]
也不是，Android8的通知样式里没有有用户图标，会看起来更紧凑一点

**Comment by MisakaSakura** [comment]
@ekibun 我记得之前有个版本是可以显示图标的emmm

**Comment by ekibun** [comment]
只有群头像能显示在右侧，用户头像不可能收集得到，以前没有以后也不会有

“作为消息通知的图标”我可能没有理解清楚，如果你使用的是原生的Android9的话，作为通知栏显示的 小图标 应该是和QQ原始图标一样的，具体布局第三方系统怎么改程序是控制不了的了
