### ISSUE TITLE
Android Q 支援

### ISSUE THREAD

**Issue by MichaelPan1026** [ekibun/QQNotifyPlus#6]
应用不能在 Android Q 中正常工作，具体为收到通知没有通知。
已授予通知访问权和Root，没有对后台进行限制。

**Comment by Fotia5230** [comment]
我也是Anroid Q，AEXv6.5，TIM
以前可以收到通知但没有声音，这几天已经不显示通知了，确定TIM实际上收到通知了，因为打开TIM立即看到了消息，没有禁用私聊消息渠道
需要log？

**Comment by 123Duo3** [comment]
Android Q禁用了通知的内源替换（即以QQ的通知显示），可以尝试禁用root权限后使用（不过这样通知圆点会没）。

**Comment by MichaelPan1026** [comment]
嗯 内源替换这个在 nevo 也遇到了同样的问题。目前已经退回 Android P。太不便捷了。
